//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_plante
    {
        public long plaId { get; set; }
        public string plaName { get; set; }
        public string plaType { get; set; }
        public string plaProtocol { get; set; }
    }
}
