//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_protocole
    {
        public long proId { get; set; }
        public string proTask { get; set; }
        public System.DateTime proDateTask { get; set; }
        public bool proIsDone { get; set; }
        public bool proToDo { get; set; }
        public long tilId { get; set; }
    
        public virtual t_tile t_tile { internal get; set; }
    }
}
