//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_tile
    {
        public t_tile()
        {
            this.t_protocole = new HashSet<t_protocole>();
        }
    
        public long tilId { get; set; }
        public string tilPlant { get; set; }
        public System.DateTime tilDate { get; set; }
        public string tilPosition { get; set; }
        public long jarId { get; set; }
    
        public virtual t_jardin t_jardin { get; set; }
        public virtual ICollection<t_protocole> t_protocole { get; set; }
    }
}
